### ISSUE TITLE
你好，请问可以用clion后续配合docker开发吗？

### ISSUE THREAD

**Issue by hr2894235132** [kris6767679/slam_in_autonomous_driving_docker#1]

**Comment by zijiechenrobotics** [comment]
Hi @hr2894235132 , thank you for your attention to this work. It is no doubt that CLion can work with docker.

Please follow the docker toolchain for more details: https://www.jetbrains.com/help/clion/clion-toolchains-in-docker.html#sample-dockerfile

And here is a tutorial in Chinese: https://www.bilibili.com/video/BV1tK4y1c7gy/?spm_id_from=333.337.search-card.all.click&vd_source=a23d841c4ace01eddfe9603b21e7891f
